/* ---------------- Template data: temples ----------------
 Each object: {id,name,img,desc,long,lat,lon}
*/
const temples = [
    { id: 'janmabhoomi', name: 'Shri Krishna Janmabhoomi', img: 'https://4.bp.blogspot.com/-T4PyIEXIfPE/Xy6PwZ-edZI/AAAAAAAA7j0/jsdt-eeVlBYffEuxzKSeYb39QXKS3uGNQCK4BGAYYCw/s1600/Krishna_Janmabhoomi_Temple_Mathura.jpg', desc: 'Birthplace of Lord Krishna.', long: 'Shri Krishna Janmabhoomi is the sacred site believed to be Krishna’s birthplace. Great for darshan and aarti timings.', lat: 27.4926, lon: 77.6737 },
    { id: 'dwarkadhish', name: 'Dwarkadhish Temple', img: 'https://www.holidify.com/images/cmsuploads/compressed/44740200661_87a6f2d457_b_20190409174705_20190409174732.jpg', desc: 'Ancient temple with beautiful architecture.', long: 'Dwarkadhish Temple features typical North Indian temple architecture and daily rituals.', lat: 27.4966, lon: 77.6733 },
    { id: 'gita-mandir', name: 'Gita Mandir (Birla Mandir)', img: 'https://images.ixigo.com/image/upload/t_thumb,f_auto/gita-mandir-images-photos-5264fc21e4b07f4c7a2a7fba.jpg', desc: 'Carvings from the Gita.', long: 'Gita Mandir displays scenes from the Bhagavad Gita across the walls.', lat: 27.5050, lon: 77.6729 },
    { id: 'vishram-ghat', name: 'Vishram Ghat', img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Vishram_Ghat.jpg/536px-Vishram_Ghat.jpg', desc: 'Holy ghat on the Yamuna.', long: 'Vishram Ghat is the riverside spot where evening aarti is held.', lat: 27.4920, lon: 77.6710 },
    { id: 'prem-mandir', name: 'Prem Mandir', img: 'https://i.pinimg.com/originals/ae/cb/f5/aecbf520f77ea2bed8f408d6e7f9275e.jpg', desc: 'Marble temple with sculptures.', long: 'Prem Mandir is a modern marble temple with carved scenes and illuminated gardens.', lat: 27.5297, lon: 77.6932 },
    { id: 'iskcon', name: 'ISKCON Vrindavan', img: 'https://mathuravrindavantourism.co.in/images/places-to-visit/headers/krishna-balaram-mandir-iskcon-vrindavan-mathura-indian-tourism-header-small.jpg', desc: 'ISKCON Krishna Balaram Mandir.', long: 'ISKCON hosts bhajans and aarti with vibrant congregations.', lat: 27.5704, lon: 77.6736 },
    { id: 'char-dham', name: 'Char Dham', img: 'https://tse2.mm.bing.net/th/id/OIP.Tpr-3-ND_e3Pul-UY_h3RQHaG2?w=474&h=438', desc: 'Char Dham replica.', long: 'Replica complex visiting spot.', lat: 27.5035, lon: 77.6700 },
    { id: 'priyakant', name: 'Priyakant Ju Temple', img: 'https://th.bing.com/th/id/OIP.mHu-dannyOaAwyXlgFGJTwHaE7?w=259&h=180', desc: 'Local shrine.', long: 'A small and historic local shrine.', lat: 27.5120, lon: 77.6750 },
    { id: 'chandrodaya', name: 'Vrindavan Chandrodaya Mandir', img: 'https://amarujalaa.com/wp-content/uploads/2025/04/Vrindavan-Chandrodaya-Mandir-Feature-1.webp', desc: 'Grand new temple project.', long: 'Chandrodaya is a massive project with cultural exhibits.', lat: 27.5689, lon: 77.6803 },
    { id: 'barsana', name: 'Barsana', img: 'https://merobrajdham.com/wp-content/uploads/2024/09/20240905_083149-1024x768.jpg', desc: 'Birthplace of Radha.', long: 'Barsana is the village associated with Radha’s pastimes.', lat: 27.6780, lon: 77.6530 },
    { id: 'gokul', name: 'Gokul', img: 'https://blessingsonthenet.com/img/uploads/aim_bn_1308912011.jpg', desc: 'Where Krishna spent childhood.', long: 'Gokul’s sites are connected to Krishna’s early life.', lat: 27.4870, lon: 77.6920 },
    { id: 'nandgaon', name: 'Nandgaon', img: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/b1/00/dc/lath-holi-extravaganza.jpg', desc: 'Village of Nandgaon.', long: 'Nandgaon is known for Holi & local traditions.', lat: 27.6650, lon: 77.6830 },
    { id: 'raman-reti', name: 'Raman Reti', img: 'https://i.imgur.com/lU9gq77.jpeg', desc: 'Sandy playground for pastimes.', long: 'Open sandy ground used for pastimes and festivals.', lat: 27.5065, lon: 77.6790 },
    { id: 'nidhivan', name: 'Nidhivan', img: 'https://i.imgur.com/rxU4Jfw.jpeg', desc: 'Mystic grove of Vrindavan.', long: 'Nidhivan is a mystic grove with local legends.', lat: 27.5698, lon: 77.6785 },
    { id: 'keshi-ghat', name: 'Keshi Ghat', img: 'https://i.imgur.com/5W5jZvm.jpeg', desc: 'Peaceful ghat and aarti spot.', long: 'Keshi Ghat is peaceful and close to important temples.', lat: 27.4929, lon: 77.6708 },
    { id: 'radha-vallabha', name: 'Radha Vallabha Temple', img: 'images/radha_vallabha.png', desc: 'Symbol of divine love.', long: 'Radha Vallabha Temple is a historic temple in Vrindavan, dedicated to the divine couple Radha and Krishna, emphasizing their oneness.', lat: 27.5800, lon: 77.7000 }
];
